- hosts: localhost
  tasks:
  - set_fact:
      nics: []
  - set_fact:
      nics: "{{ nics + [item] }}"
    loop: "{{ ansible_interfaces | difference(['lo', 'virbr0']) }}"

  - debug:
      var: ansible_{{ item }}.ipv4.address
      #msg: "{{ item }} IP address: {{ vars['ansible_' + item].ipv4.address }}"
    loop: '{{ nics }}'
