# with_item flattens only one level while loop can handle multiple levels with "flatten" filter
- hosts: localhost
  vars: 
    nested_list:
    - [[["a1","a2"],["a3"]],[["b1"]]]
    - [[["c1","c2"]]]
  tasks:
  - name: debug task - with_items
    debug: 
      msg: "Item ==> {{ item }}"
    with_items: "{{ nested_list }}"

  - name: debug task1 - loop with level 1 - same with with_items
    debug:
      msg: "{{ loop_index }} - {{ item }}"
    loop: "{{ nested_list | flatten(levels=1) }}"
    loop_control:
      index_var: loop_index

  - name: debug task2 - loop with level 2
    debug:
      msg: "{{ loop_index }} - {{ item }}"
    loop: "{{ nested_list | flatten(levels=2) }}"
    loop_control:
      index_var: loop_index

  - name: debug task2 - loop with level 3
    debug:
      msg: "{{ loop_index }} - {{ item }}"
    loop: "{{ nested_list | flatten(levels=3) }}"
    loop_control:
      index_var: loop_index
