# with_item vs loop with flatten
- hosts: localhost
  gather_facts: false
  vars: 
    app_a_tmp_files:
      - /tmp/app_a.log
      - /tmp/app_a.pid
    app_b_tmp_files:
      - /tmp/app_b.cache
    app_c_tmp_files:
      - /tmp/app_c.tmp
      - /tmp/app_c.lock
    list_of_lists:
      - "{{ app_a_tmp_files }}"
      - "{{ app_b_tmp_files }}"
      - "{{ app_c_tmp_files }}"
  tasks:
  - debug: 
      var: item
    with_items: "{{ list_of_lists }}"     # 6 kere doner

  - debug:
      var: item
    #loop: "{{ list_of_lists | flatten(levels=1) }}"  # 6 kere doner
    loop: "{{ list_of_lists }}"  # 3 kere doner

