- hosts: localhost
  vars:
    my_yaml1: "{{ lookup('ansible.builtin.file', 'file.yml') | type_debug}}"
    my_yaml2: "{{ lookup('ansible.builtin.file', 'file.yml') | from_yaml | type_debug}}"
    my_yaml3: "{{ query('ansible.builtin.file', 'file.yml') | to_yaml | type_debug}}"
  tasks:
  - debug:
      msg: '{{ my_yaml1 }} - {{ my_yaml2 }} -  {{ my_yaml3 }}'

  - debug:
      msg: '{{ item.0 }}'
    loop: 
    - "{{ query('ansible.builtin.lines', 'cat hosts1') }}"
    - "{{ query('ansible.builtin.lines', 'cat hosts2') }}"

  - copy:
      content: "{{ lookup('ansible.builtin.file', 'file.yml') }}"
      dest: /tmp/file1
  - copy:
      content: "{{ lookup('ansible.builtin.file', 'file.yml') | from_yaml }}"
      dest: /tmp/file2
  - copy:
      content: "{{ lookup('ansible.builtin.file', 'file.yml') | to_yaml }}"
      dest: /tmp/file3
