# Don't forget to install the following before demo:
# ansible-galaxy collection install ansible.netcommon
# pip3.9 install netaddr
- hosts: localhost
  gather_facts: no
  vars:
    listips:
      - 192.168.2.1
      - 10.0.0.128/25
      - 172.24.10.0/255.255.255.0
      - 172.24.10.0/255.255.255.255
      - ff02::1
      - ::1
      - 2001::1/64
      - 2001::/64
      - www.redhat.com
  tasks:
  - debug:
      msg: "{{ listips | ansible.utils.ipaddr('private') }}"
