- name: Gather facts for everyone
  hosts: webservers
  gather_facts: true

- name: The next play, does not gather facts
  hosts: all

  tasks:
    - name: Show that we still know the facts
      ansible.builtin.debug:
        var: ansible_fqdn
