- hosts: all
  gather_facts: false
  vars:
    welcome: Hello
    path: /var/www/html/index.html
  tasks:
  - dnf:
      name: httpd
      state: installed
  - copy:
      content: "{{ welcome }}\n"
      dest: "{{ path }}"
  - service:
      name: httpd
      state: started
  - firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: enabled
