- name: Ping on webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Webhook trigger
      condition: event.payload.msg == "ping"
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
